import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Practice nextJs Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container max-w-2xl m-auto px-4 py-6">
          <nav className="flex space-x-4 text-xl">
            <Link className=" hover:bg-slate-100 p-1 rounded-md" href="/">
              About
            </Link>
            <Link className=" hover:bg-slate-100 p-1 rounded-md" href="posts">
              Posts
            </Link>
          </nav>
        </div>

        {children}
      </body>
    </html>
  );
}
